contentColumnType: smallint(2)
fieldGroup: 8f033c66-fa69-45dd-b77d-4736d7c23427 # Common
handle: identifier
instructions: ''
name: Identifier
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: '40'
  min: '1'
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
