enableVersioning: true
handle: aboutUs
name: 'About us'
propagationMethod: all
siteSettings:
  4a80df2d-c2b9-46bf-94f7-eecc714b2b62: # Nederlands
    enabledByDefault: true
    hasUrls: true
    template: about-us/_entry
    uriFormat: about-us
  81d10473-13e6-46a6-acd3-0fd9c7ab3729: # English
    enabledByDefault: true
    hasUrls: true
    template: about-us/_entry
    uriFormat: about-us
type: single
