enableVersioning: true
handle: artObjects
name: 'Art Objects'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4a80df2d-c2b9-46bf-94f7-eecc714b2b62: # Nederlands
    enabledByDefault: true
    hasUrls: true
    template: art-objects/_entry
    uriFormat: kunstwerken
  81d10473-13e6-46a6-acd3-0fd9c7ab3729: # English
    enabledByDefault: true
    hasUrls: true
    template: art-objects/_entry
    uriFormat: art-objects
type: single
