enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  4a80df2d-c2b9-46bf-94f7-eecc714b2b62: # Nederlands
    enabledByDefault: true
    hasUrls: true
    template: homepage/_entry
    uriFormat: __home__
  81d10473-13e6-46a6-acd3-0fd9c7ab3729: # English
    enabledByDefault: true
    hasUrls: true
    template: homepage/_entry
    uriFormat: __home__
type: single
