enableVersioning: true
handle: librarian
name: Librarian
propagationMethod: siteGroup
siteSettings:
  4a80df2d-c2b9-46bf-94f7-eecc714b2b62: # Nederlands
    enabledByDefault: true
    hasUrls: true
    template: librarian/_entry
    uriFormat: 'bibliothecaris/{slug}'
  81d10473-13e6-46a6-acd3-0fd9c7ab3729: # English
    enabledByDefault: true
    hasUrls: true
    template: librarian/_entry
    uriFormat: 'librarian/{slug}'
structure:
  maxLevels: null
  uid: 68f48993-2e70-4557-9859-48a87e50f9f0
type: structure
